// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ContosoUniversity.Data;

namespace ContosoUniversity.Migrations
{
   [DbContext(typeof(ContosoUniversityContext))]
   partial class ContosoUniversityContextModelSnapshot : ModelSnapshot
   {
      protected override void BuildModel(ModelBuilder modelBuilder)
      {
#pragma warning disable 612, 618
         modelBuilder
             .HasAnnotation("ProductVersion", "3.1.2");

         modelBuilder.Entity("ContosoUniversity.Models.Movie", b =>
             {
                b.Property<int>("Id")
                       .ValueGeneratedOnAdd()
                       .HasColumnType("INTEGER");

                b.Property<string>("Genre")
                       .HasColumnType("TEXT");

                b.Property<string>("ImagePath")
                       .HasColumnType("TEXT");

                b.Property<decimal>("Price")
                       .HasColumnType("decimal(18, 2)");

                b.Property<string>("Rating")
                       .HasColumnType("TEXT");

                b.Property<DateTime>("ReleaseDate")
                       .HasColumnType("TEXT");

                b.Property<string>("Title")
                       .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Movie");
             });
#pragma warning restore 612, 618
      }
   }
}
